name: fancy_password_field
description: A highly customizable password control input widget.
version: 1.0.0+5
repository: https://github.com/rodrigobastosv/fancy_password_field

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  password_strength: ^0.2.0
  font_awesome_flutter: ^9.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

scripts: derry.yaml

flutter:
